# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chess_room_window.ui'
#
# Created: Mon May 26 15:59:29 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ChessRoomWindow(object):
    def setupUi(self, ChessRoomWindow):
        ChessRoomWindow.setObjectName(_fromUtf8("ChessRoomWindow"))
        ChessRoomWindow.resize(948, 800)
        ChessRoomWindow.setStyleSheet(_fromUtf8("background-color: #517191;"))
        self.RoomTitle = QtGui.QLabel(ChessRoomWindow)
        self.RoomTitle.setGeometry(QtCore.QRect(205, 10, 541, 71))
        self.RoomTitle.setStyleSheet(_fromUtf8("background-color: #E2C9A5;\n"
"\n"
"\n"
"font:75 28pt \"微软雅黑\";"))
        self.RoomTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.RoomTitle.setObjectName(_fromUtf8("RoomTitle"))
        self.ChessBoardBackground = QtGui.QWidget(ChessRoomWindow)
        self.ChessBoardBackground.setGeometry(QtCore.QRect(200, 90, 551, 531))
        self.ChessBoardBackground.setStyleSheet(_fromUtf8("background-color: #8D4A27;"))
        self.ChessBoardBackground.setObjectName(_fromUtf8("ChessBoardBackground"))
        self.ChessBoard = QtGui.QWidget(self.ChessBoardBackground)
        self.ChessBoard.setGeometry(QtCore.QRect(30, 20, 490, 490))
        self.ChessBoard.setStyleSheet(_fromUtf8("background-color: #DEBA6A;"))
        self.ChessBoard.setObjectName(_fromUtf8("ChessBoard"))
        self.ChatBox = QtGui.QWidget(ChessRoomWindow)
        self.ChatBox.setGeometry(QtCore.QRect(10, 630, 921, 161))
        self.ChatBox.setStyleSheet(_fromUtf8("background-color: #E2C9A5;"))
        self.ChatBox.setObjectName(_fromUtf8("ChatBox"))
        self.InputText = QtGui.QTextEdit(self.ChatBox)
        self.InputText.setGeometry(QtCore.QRect(10, 120, 821, 31))
        self.InputText.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.InputText.setObjectName(_fromUtf8("InputText"))
        self.SendButton = QtGui.QPushButton(self.ChatBox)
        self.SendButton.setGeometry(QtCore.QRect(840, 120, 71, 31))
        self.SendButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 170, 127);\n"
"font: 75 11pt \"微软雅黑\";"))
        self.SendButton.setObjectName(_fromUtf8("SendButton"))
        self.MessageText = QtGui.QPlainTextEdit(self.ChatBox)
        self.MessageText.setGeometry(QtCore.QRect(10, 10, 901, 101))
        self.MessageText.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.MessageText.setObjectName(_fromUtf8("MessageText"))
        self.MyInfoBox = QtGui.QWidget(ChessRoomWindow)
        self.MyInfoBox.setGeometry(QtCore.QRect(10, 320, 181, 301))
        self.MyInfoBox.setStyleSheet(_fromUtf8("background-color: #E2C9A5;"))
        self.MyInfoBox.setObjectName(_fromUtf8("MyInfoBox"))
        self.LabelNickName = QtGui.QLabel(self.MyInfoBox)
        self.LabelNickName.setGeometry(QtCore.QRect(20, 90, 51, 31))
        self.LabelNickName.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.LabelNickName.setObjectName(_fromUtf8("LabelNickName"))
        self.LabelScore = QtGui.QLabel(self.MyInfoBox)
        self.LabelScore.setGeometry(QtCore.QRect(20, 120, 51, 31))
        self.LabelScore.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.LabelScore.setObjectName(_fromUtf8("LabelScore"))
        self.LabelWinTime = QtGui.QLabel(self.MyInfoBox)
        self.LabelWinTime.setGeometry(QtCore.QRect(20, 150, 51, 31))
        self.LabelWinTime.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.LabelWinTime.setObjectName(_fromUtf8("LabelWinTime"))
        self.LabelDrawTime = QtGui.QLabel(self.MyInfoBox)
        self.LabelDrawTime.setGeometry(QtCore.QRect(20, 180, 51, 31))
        self.LabelDrawTime.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.LabelDrawTime.setObjectName(_fromUtf8("LabelDrawTime"))
        self.LabelLoseTime = QtGui.QLabel(self.MyInfoBox)
        self.LabelLoseTime.setGeometry(QtCore.QRect(20, 210, 51, 31))
        self.LabelLoseTime.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.LabelLoseTime.setObjectName(_fromUtf8("LabelLoseTime"))
        self.Draw = QtGui.QLabel(self.MyInfoBox)
        self.Draw.setGeometry(QtCore.QRect(80, 180, 81, 31))
        self.Draw.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.Draw.setObjectName(_fromUtf8("Draw"))
        self.NickName = QtGui.QLabel(self.MyInfoBox)
        self.NickName.setGeometry(QtCore.QRect(80, 90, 81, 31))
        self.NickName.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.NickName.setObjectName(_fromUtf8("NickName"))
        self.Score = QtGui.QLabel(self.MyInfoBox)
        self.Score.setGeometry(QtCore.QRect(80, 120, 81, 31))
        self.Score.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.Score.setObjectName(_fromUtf8("Score"))
        self.LoseTime = QtGui.QLabel(self.MyInfoBox)
        self.LoseTime.setGeometry(QtCore.QRect(80, 210, 81, 31))
        self.LoseTime.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.LoseTime.setObjectName(_fromUtf8("LoseTime"))
        self.WinTime = QtGui.QLabel(self.MyInfoBox)
        self.WinTime.setGeometry(QtCore.QRect(80, 150, 81, 31))
        self.WinTime.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.WinTime.setObjectName(_fromUtf8("WinTime"))
        self.LabelSide = QtGui.QLabel(self.MyInfoBox)
        self.LabelSide.setGeometry(QtCore.QRect(20, 60, 51, 31))
        self.LabelSide.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.LabelSide.setObjectName(_fromUtf8("LabelSide"))
        self.Side = QtGui.QLabel(self.MyInfoBox)
        self.Side.setGeometry(QtCore.QRect(80, 60, 81, 31))
        self.Side.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.Side.setObjectName(_fromUtf8("Side"))
        self.State = QtGui.QLabel(self.MyInfoBox)
        self.State.setGeometry(QtCore.QRect(80, 240, 81, 31))
        self.State.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";\n"
"color: rgb(255, 0, 0);"))
        self.State.setObjectName(_fromUtf8("State"))
        self.LabelState = QtGui.QLabel(self.MyInfoBox)
        self.LabelState.setGeometry(QtCore.QRect(20, 240, 51, 31))
        self.LabelState.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.LabelState.setObjectName(_fromUtf8("LabelState"))
        self.LabelState_3 = QtGui.QLabel(self.MyInfoBox)
        self.LabelState_3.setGeometry(QtCore.QRect(50, 20, 51, 31))
        self.LabelState_3.setStyleSheet(_fromUtf8("font: 16pt \"微软雅黑\";"))
        self.LabelState_3.setObjectName(_fromUtf8("LabelState_3"))
        self.ControlBox = QtGui.QWidget(ChessRoomWindow)
        self.ControlBox.setGeometry(QtCore.QRect(760, 10, 171, 611))
        self.ControlBox.setStyleSheet(_fromUtf8("background-color: #E2C9A5;"))
        self.ControlBox.setObjectName(_fromUtf8("ControlBox"))
        self.ReadyButton = QtGui.QPushButton(self.ControlBox)
        self.ReadyButton.setGeometry(QtCore.QRect(20, 400, 131, 51))
        self.ReadyButton.setStyleSheet(_fromUtf8("font: 16pt \"微软雅黑\";"))
        self.ReadyButton.setObjectName(_fromUtf8("ReadyButton"))
        self.AdmitDefeatButton = QtGui.QPushButton(self.ControlBox)
        self.AdmitDefeatButton.setGeometry(QtCore.QRect(20, 470, 131, 51))
        self.AdmitDefeatButton.setStyleSheet(_fromUtf8("font: 16pt \"微软雅黑\";"))
        self.AdmitDefeatButton.setObjectName(_fromUtf8("AdmitDefeatButton"))
        self.UndoButton = QtGui.QPushButton(self.ControlBox)
        self.UndoButton.setGeometry(QtCore.QRect(20, 540, 131, 51))
        self.UndoButton.setStyleSheet(_fromUtf8("font: 16pt \"微软雅黑\" ;"))
        self.UndoButton.setObjectName(_fromUtf8("UndoButton"))
        self.LiveText = QtGui.QPlainTextEdit(self.ControlBox)
        self.LiveText.setGeometry(QtCore.QRect(10, 50, 151, 341))
        self.LiveText.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"微软雅黑\";"))
        self.LiveText.setReadOnly(True)
        self.LiveText.setPlainText(_fromUtf8(""))
        self.LiveText.setObjectName(_fromUtf8("LiveText"))
        self.LiveTitle = QtGui.QLabel(self.ControlBox)
        self.LiveTitle.setGeometry(QtCore.QRect(10, 10, 151, 31))
        self.LiveTitle.setStyleSheet(_fromUtf8("font: 13pt \"微软雅黑\";"))
        self.LiveTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.LiveTitle.setObjectName(_fromUtf8("LiveTitle"))
        self.EnemyInfoBox = QtGui.QWidget(ChessRoomWindow)
        self.EnemyInfoBox.setGeometry(QtCore.QRect(10, 10, 181, 301))
        self.EnemyInfoBox.setStyleSheet(_fromUtf8("background-color: #E2C9A5;"))
        self.EnemyInfoBox.setObjectName(_fromUtf8("EnemyInfoBox"))
        self.LabelNickName_2 = QtGui.QLabel(self.EnemyInfoBox)
        self.LabelNickName_2.setGeometry(QtCore.QRect(20, 90, 51, 31))
        self.LabelNickName_2.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.LabelNickName_2.setObjectName(_fromUtf8("LabelNickName_2"))
        self.LabelScore_2 = QtGui.QLabel(self.EnemyInfoBox)
        self.LabelScore_2.setGeometry(QtCore.QRect(20, 120, 51, 31))
        self.LabelScore_2.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.LabelScore_2.setObjectName(_fromUtf8("LabelScore_2"))
        self.LabelWinTime_2 = QtGui.QLabel(self.EnemyInfoBox)
        self.LabelWinTime_2.setGeometry(QtCore.QRect(20, 150, 51, 31))
        self.LabelWinTime_2.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.LabelWinTime_2.setObjectName(_fromUtf8("LabelWinTime_2"))
        self.LabelDrawTime_2 = QtGui.QLabel(self.EnemyInfoBox)
        self.LabelDrawTime_2.setGeometry(QtCore.QRect(20, 180, 51, 31))
        self.LabelDrawTime_2.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.LabelDrawTime_2.setObjectName(_fromUtf8("LabelDrawTime_2"))
        self.LabelLoseTime_2 = QtGui.QLabel(self.EnemyInfoBox)
        self.LabelLoseTime_2.setGeometry(QtCore.QRect(20, 210, 51, 31))
        self.LabelLoseTime_2.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.LabelLoseTime_2.setObjectName(_fromUtf8("LabelLoseTime_2"))
        self.EnemyDrawTime = QtGui.QLabel(self.EnemyInfoBox)
        self.EnemyDrawTime.setGeometry(QtCore.QRect(80, 180, 81, 31))
        self.EnemyDrawTime.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.EnemyDrawTime.setObjectName(_fromUtf8("EnemyDrawTime"))
        self.EnemyNickName = QtGui.QLabel(self.EnemyInfoBox)
        self.EnemyNickName.setGeometry(QtCore.QRect(80, 90, 81, 31))
        self.EnemyNickName.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.EnemyNickName.setObjectName(_fromUtf8("EnemyNickName"))
        self.EnemyScore = QtGui.QLabel(self.EnemyInfoBox)
        self.EnemyScore.setGeometry(QtCore.QRect(80, 120, 81, 31))
        self.EnemyScore.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.EnemyScore.setObjectName(_fromUtf8("EnemyScore"))
        self.EnemyLoseTime = QtGui.QLabel(self.EnemyInfoBox)
        self.EnemyLoseTime.setGeometry(QtCore.QRect(80, 210, 81, 31))
        self.EnemyLoseTime.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.EnemyLoseTime.setObjectName(_fromUtf8("EnemyLoseTime"))
        self.EnemyWinTime = QtGui.QLabel(self.EnemyInfoBox)
        self.EnemyWinTime.setGeometry(QtCore.QRect(80, 150, 81, 31))
        self.EnemyWinTime.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.EnemyWinTime.setObjectName(_fromUtf8("EnemyWinTime"))
        self.LabelSide_2 = QtGui.QLabel(self.EnemyInfoBox)
        self.LabelSide_2.setGeometry(QtCore.QRect(20, 60, 51, 31))
        self.LabelSide_2.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.LabelSide_2.setObjectName(_fromUtf8("LabelSide_2"))
        self.EnemySide = QtGui.QLabel(self.EnemyInfoBox)
        self.EnemySide.setGeometry(QtCore.QRect(80, 60, 81, 31))
        self.EnemySide.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.EnemySide.setObjectName(_fromUtf8("EnemySide"))
        self.EnemyState = QtGui.QLabel(self.EnemyInfoBox)
        self.EnemyState.setGeometry(QtCore.QRect(80, 240, 81, 31))
        self.EnemyState.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";\n"
"color: rgb(255, 0, 0);"))
        self.EnemyState.setObjectName(_fromUtf8("EnemyState"))
        self.LabelState_2 = QtGui.QLabel(self.EnemyInfoBox)
        self.LabelState_2.setGeometry(QtCore.QRect(20, 240, 51, 31))
        self.LabelState_2.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";"))
        self.LabelState_2.setObjectName(_fromUtf8("LabelState_2"))
        self.LabelState_4 = QtGui.QLabel(self.EnemyInfoBox)
        self.LabelState_4.setGeometry(QtCore.QRect(50, 20, 51, 31))
        self.LabelState_4.setStyleSheet(_fromUtf8("font: 16pt \"微软雅黑\";"))
        self.LabelState_4.setObjectName(_fromUtf8("LabelState_4"))

        self.retranslateUi(ChessRoomWindow)
        QtCore.QMetaObject.connectSlotsByName(ChessRoomWindow)
        ChessRoomWindow.setTabOrder(self.InputText, self.SendButton)
        ChessRoomWindow.setTabOrder(self.SendButton, self.MessageText)
        ChessRoomWindow.setTabOrder(self.MessageText, self.ReadyButton)
        ChessRoomWindow.setTabOrder(self.ReadyButton, self.AdmitDefeatButton)
        ChessRoomWindow.setTabOrder(self.AdmitDefeatButton, self.UndoButton)
        ChessRoomWindow.setTabOrder(self.UndoButton, self.LiveText)

    def retranslateUi(self, ChessRoomWindow):
        ChessRoomWindow.setWindowTitle(_translate("ChessRoomWindow", "Form", None))
        self.RoomTitle.setText(_translate("ChessRoomWindow", "<html><head/><body><p>决 <span style=\" color:#ffffff;\">战</span> 五 <span style=\" color:#ffffff;\">子</span> 棋</p></body></html>", None))
        self.SendButton.setText(_translate("ChessRoomWindow", "发 送", None))
        self.LabelNickName.setText(_translate("ChessRoomWindow", "昵称：", None))
        self.LabelScore.setText(_translate("ChessRoomWindow", "积分：", None))
        self.LabelWinTime.setText(_translate("ChessRoomWindow", "胜绩：", None))
        self.LabelDrawTime.setText(_translate("ChessRoomWindow", "平绩：", None))
        self.LabelLoseTime.setText(_translate("ChessRoomWindow", "败绩：", None))
        self.Draw.setText(_translate("ChessRoomWindow", "平绩", None))
        self.NickName.setText(_translate("ChessRoomWindow", "昵称", None))
        self.Score.setText(_translate("ChessRoomWindow", "积分", None))
        self.LoseTime.setText(_translate("ChessRoomWindow", "败绩", None))
        self.WinTime.setText(_translate("ChessRoomWindow", "胜绩", None))
        self.LabelSide.setText(_translate("ChessRoomWindow", "方向：", None))
        self.Side.setText(_translate("ChessRoomWindow", "方向", None))
        self.State.setText(_translate("ChessRoomWindow", "状态", None))
        self.LabelState.setText(_translate("ChessRoomWindow", "状态：", None))
        self.LabelState_3.setText(_translate("ChessRoomWindow", "我 方", None))
        self.ReadyButton.setText(_translate("ChessRoomWindow", "准 备", None))
        self.AdmitDefeatButton.setText(_translate("ChessRoomWindow", "认 输", None))
        self.UndoButton.setText(_translate("ChessRoomWindow", "悔 棋", None))
        self.LiveTitle.setText(_translate("ChessRoomWindow", "<html><head/><body><p><span style=\" font-weight:600;\">文 字 直 播</span></p></body></html>", None))
        self.LabelNickName_2.setText(_translate("ChessRoomWindow", "昵称：", None))
        self.LabelScore_2.setText(_translate("ChessRoomWindow", "积分：", None))
        self.LabelWinTime_2.setText(_translate("ChessRoomWindow", "胜绩：", None))
        self.LabelDrawTime_2.setText(_translate("ChessRoomWindow", "平绩：", None))
        self.LabelLoseTime_2.setText(_translate("ChessRoomWindow", "败绩：", None))
        self.EnemyDrawTime.setText(_translate("ChessRoomWindow", "平绩", None))
        self.EnemyNickName.setText(_translate("ChessRoomWindow", "昵称", None))
        self.EnemyScore.setText(_translate("ChessRoomWindow", "积分", None))
        self.EnemyLoseTime.setText(_translate("ChessRoomWindow", "败绩", None))
        self.EnemyWinTime.setText(_translate("ChessRoomWindow", "胜绩", None))
        self.LabelSide_2.setText(_translate("ChessRoomWindow", "方向：", None))
        self.EnemySide.setText(_translate("ChessRoomWindow", "方向", None))
        self.EnemyState.setText(_translate("ChessRoomWindow", "状态", None))
        self.LabelState_2.setText(_translate("ChessRoomWindow", "状态：", None))
        self.LabelState_4.setText(_translate("ChessRoomWindow", "敌 方", None))

